Android: Fix libcxxabi include directory
When compiling with libcxx, add libcxxabi include directory to include path
instead of gabi++. Fixes errors like

    error: no member named '__cxa_demangle' in namespace '__cxxabiv1'